/** Canonical attention inventories. These records are source contracts, not summaries. */

export type AttentionSeverity = 'info' | 'warning' | 'error';
export type AttentionClockEffect = 'recorded' | 'passive';
export type AttentionSourceOwner = 'design' | 'app' | 'generated' | 'module';
export interface AttentionMarker { readonly owner:AttentionSourceOwner; readonly text:string; }
export interface AttentionWiringRow { readonly id:string; readonly control:string; readonly mode:string|null; readonly designMarker:AttentionMarker; readonly controlConstruction:AttentionMarker; readonly durableKey:AttentionMarker; readonly writerMarkers:readonly AttentionMarker[]; readonly setterMarkers:readonly AttentionMarker[]; readonly consumerMarkers:readonly AttentionMarker[]; }
const marker = (owner:AttentionSourceOwner, text:string): AttentionMarker => ({ owner, text });
export const ATTENTION_WIRING: readonly AttentionWiringRow[] = [
  { id:'focus', control:'att_focus', mode:'focus', designMarker:marker('design',"ctl('att_focus','Focus','switch',false"), controlConstruction:marker('app',"'att_focus': 'focus'"), durableKey:marker('module',"focus: 'console.attention.focus'"), writerMarkers:[marker('app',"control?.id?.startsWith('att_') && typeof value === 'boolean'"), marker('app',"setModeEnabled(this.durableStorage.storage, mode, value);"), marker('app',"this.attentionWrite(`${MODE_SETTING_PREFIX}${mode}`, value ? 'on' : 'off');"), marker('generated',"this.onUserMutation('control:' + (c.id || 'unknown'));" )], setterMarkers:[marker('app',"setModeEnabled(this.durableStorage.storage, mode, value);")], consumerMarkers:[marker('module',"dimInactive: modeEnabled(storage, 'focus'),"), marker('app','[data-attention-inactive="true"] { opacity'), marker('app',"element.dataset.attentionInactive = presentation.dimInactive ? 'true' : 'false';")] },
  { id:'low-stimulation', control:'att_low', mode:'lowStimulation', designMarker:marker('design',"ctl('att_low','Low stimulation','switch',false"), controlConstruction:marker('app',"'att_low': 'lowStimulation'"), durableKey:marker('module',"lowStimulation: 'console.attention.lowStimulation'"), writerMarkers:[marker('app',"control?.id?.startsWith('att_') && typeof value === 'boolean'"), marker('app',"setModeEnabled(this.durableStorage.storage, mode, value);"), marker('app',"this.attentionWrite(`${MODE_SETTING_PREFIX}${mode}`, value ? 'on' : 'off');"), marker('generated',"this.onUserMutation('control:' + (c.id || 'unknown'));" )], setterMarkers:[marker('app',"setModeEnabled(this.durableStorage.storage, mode, value);")], consumerMarkers:[marker('module',"reduceMotion: low || platform.prefersReducedMotion === true,"), marker('module',"quietNotifications: low,"), marker('app',"document.body.classList.toggle('attention-low-stimulation', presentation.quietNotifications);"), marker('app',"if (severity === 'info' && modeEnabled(this.durableStorage.storage, 'lowStimulation')) return;\n      this.baseToast(message, severity);"), marker('app',"if (severity === 'info' && modeEnabled(this.durableStorage.storage, 'lowStimulation')) return;\n      this.baseFire(title, body, severity);"), marker('app',"if (severity !== 'info') this.attentionRecordNotice(severity, 'Notification', message, spans);"), marker('app',"if (severity !== 'info') this.attentionRecordNotice(severity, title, body, spans);"), marker('app',"this.baseToast(message, severity);"), marker('app',"this.baseFire(title, body, severity);")] },
  { id:'time-awareness', control:'att_time', mode:'timeAwareness', designMarker:marker('design',"ctl('att_time','Time awareness','switch',false"), controlConstruction:marker('app',"'att_time': 'timeAwareness'"), durableKey:marker('module',"timeAwareness: 'console.attention.timeAwareness'"), writerMarkers:[marker('app',"control?.id?.startsWith('att_') && typeof value === 'boolean'"), marker('app',"setModeEnabled(this.durableStorage.storage, mode, value);"), marker('app',"this.attentionWrite(`${MODE_SETTING_PREFIX}${mode}`, value ? 'on' : 'off');"), marker('generated',"this.onUserMutation('control:' + (c.id || 'unknown'));" )], setterMarkers:[marker('app',"setModeEnabled(this.durableStorage.storage, mode, value);")], consumerMarkers:[marker('module',"showElapsedTime: modeEnabled(storage, 'timeAwareness'),"), marker('app',"if (presentation.showElapsedTime) {"), marker('app',"meta.dataset.attentionMeta = 'true';"), marker('app','Session elapsed:')] },
  { id:'one-thing', control:'att_one', mode:'oneThing', designMarker:marker('design',"ctl('att_one','One thing at a time','switch',false"), controlConstruction:marker('app',"'att_one': 'oneThing'"), durableKey:marker('module',"oneThing: 'console.attention.oneThing'"), writerMarkers:[marker('app',"control?.id?.startsWith('att_') && typeof value === 'boolean'"), marker('app',"setModeEnabled(this.durableStorage.storage, mode, value);"), marker('app',"this.attentionWrite(`${MODE_SETTING_PREFIX}${mode}`, value ? 'on' : 'off');"), marker('generated',"this.onUserMutation('control:' + (c.id || 'unknown'));" )], setterMarkers:[marker('app',"setModeEnabled(this.durableStorage.storage, mode, value);")], consumerMarkers:[marker('module',"showNextAction: modeEnabled(storage, 'oneThing'),"), marker('app',"if (presentation.showNextAction) {"), marker('app',"action.dataset.attentionNext = 'true';"), marker('app',"action.textContent = chosen ? `Next action: ${chosen}` : 'Next action: none chosen yet.';")] },
  { id:'momentum', control:'att_momentum', mode:'momentum', designMarker:marker('design',"ctl('att_momentum','Momentum','switch',false"), controlConstruction:marker('app',"'att_momentum': 'momentum'"), durableKey:marker('module',"momentum: 'console.attention.momentum'"), writerMarkers:[marker('app',"control?.id?.startsWith('att_') && typeof value === 'boolean'"), marker('app',"setModeEnabled(this.durableStorage.storage, mode, value);"), marker('app',"this.attentionWrite(`${MODE_SETTING_PREFIX}${mode}`, value ? 'on' : 'off');"), marker('generated',"this.onUserMutation('control:' + (c.id || 'unknown'));" )], setterMarkers:[marker('app',"setModeEnabled(this.durableStorage.storage, mode, value);")], consumerMarkers:[marker('module',"if (!modeEnabled(storage, 'momentum')) return quiet;"), marker('app',"const prompt = momentumPrompt("), marker('app',"button.addEventListener('click', () => this.attentionSnooze(), { once: true });"), marker('app','Not now for')] },
  { id:'next-action', control:'att_next', mode:null, designMarker:marker('design',"ctl('att_next','Current next action','text',''"), controlConstruction:marker('app',"'att_next': 'nextAction'"), durableKey:marker('module',"nextAction: 'console.attention.nextAction'"), writerMarkers:[marker('app',"onUserMutation = (_source = 'unknown')"), marker('generated',"this.onUserMutation('control:' + (c.id || 'unknown'));" )], setterMarkers:[marker('app',"if (control?.id === 'att_next' && typeof value === 'string') {"), marker('app',"setNextAction(this.durableStorage.storage, value);"), marker('app',"this.attentionWrite(NEXT_ACTION_SETTING_KEY, value.trim().slice(0, NEXT_ACTION_MAX_LENGTH) || null);")], consumerMarkers:[marker('app',"const chosen = nextAction(this.durableStorage.storage);"), marker('app',"action.textContent = chosen ? `Next action: ${chosen}` : 'Next action: none chosen yet.';")] }
];
export const ATTENTION_MUTATION_ACTIONS = [
  { action:'set', key:'canvasTool', state:'canvasTool' }, { action:'set', key:'grid', state:'grid' }, { action:'set', key:'snap', state:'snap' }, { action:'set', key:'guides', state:'guides' }, { action:'set', key:'minimap', state:'minimap' }, { action:'set', key:'layer', state:'layer' }, { action:'set', key:'zoom', state:'zoom' }, { action:'set', key:'pinned', state:'pinned' }, { action:'set', key:'dock', state:'dock' }, { action:'set', key:'fullscreen', state:'fullscreen' }, { action:'set', key:'branch', state:'branch' }, { action:'set', key:'sortList', state:'sortList' },
] as const;
export interface AttentionMutationInventoryRow { readonly file:string; readonly line:number; readonly argument:string; readonly occurrence:number; readonly state:string; readonly clockEffect:AttentionClockEffect; }
export const ATTENTION_MUTATION_INVENTORY: readonly AttentionMutationInventoryRow[] = [
  { file: 'App.tsx', line: 371, argument: "'attention-history-clear'", occurrence: 1, state: 'noticeHistory', clockEffect: 'recorded' },
  { file: 'App.tsx', line: 895, argument: "'vocabulary-load'", occurrence: 1, state: 'vocabularyCache', clockEffect: 'recorded' },
  { file: 'App.tsx', line: 908, argument: "'vocabulary-clear'", occurrence: 1, state: 'vocabularyCache', clockEffect: 'recorded' },
  { file: 'App.tsx', line: 971, argument: "'support-ticket'", occurrence: 1, state: 'supportTickets', clockEffect: 'recorded' },
  { file: 'App.tsx', line: 1101, argument: "'server-add'", occurrence: 1, state: 'servers', clockEffect: 'recorded' },
  { file: 'App.tsx', line: 1114, argument: "'server-remove'", occurrence: 1, state: 'servers', clockEffect: 'recorded' },
  { file: 'App.tsx', line: 1175, argument: "'onboarding-connect'", occurrence: 1, state: 'servers', clockEffect: 'recorded' },
  { file: 'App.tsx', line: 1251, argument: "'onboarding-deploy'", occurrence: 1, state: 'runtimeConfiguration', clockEffect: 'recorded' },
  { file: 'App.tsx', line: 1425, argument: "'authenticator-pair'", occurrence: 1, state: 'authenticator', clockEffect: 'recorded' },
  { file: 'App.tsx', line: 1464, argument: "'lock-create'", occurrence: 1, state: 'locks', clockEffect: 'recorded' },
  { file: 'App.tsx', line: 1523, argument: "'lock-remove'", occurrence: 1, state: 'locks', clockEffect: 'recorded' },
  { file: 'App.tsx', line: 1606, argument: "'endpoint-write'", occurrence: 1, state: 'endpointConfiguration', clockEffect: 'recorded' },
  { file: 'App.tsx', line: 2160, argument: "'appearance-random'", occurrence: 1, state: 'appearance', clockEffect: 'recorded' },
  { file: 'App.tsx', line: 2177, argument: "'appearance-reset'", occurrence: 1, state: 'appearance', clockEffect: 'recorded' },
  { file: 'App.tsx', line: 2183, argument: "'appearance-save'", occurrence: 1, state: 'appearance', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4022, argument: "'set:' + k", occurrence: 1, state: 'generatedUserMutationKey', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4045, argument: "'control:' + (c.id || 'unknown')", occurrence: 1, state: 'controlValues', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4160, argument: "'layout:resize'", occurrence: 1, state: 'dlgSize', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4167, argument: "'layout:move'", occurrence: 1, state: 'dlgPos', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4222, argument: "'layout:dock'", occurrence: 1, state: 'dlgDock', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4355, argument: "'appearance:random'", occurrence: 1, state: 'appearanceValues', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4368, argument: "'appearance:colour'", occurrence: 1, state: 'tabColoursOrGroups', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4381, argument: "'lock:unlock'", occurrence: 1, state: 'locks', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4385, argument: "'canvas:edge'", occurrence: 1, state: 'edgeList', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4394, argument: "'canvas:move'", occurrence: 1, state: 'nodePos', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4667, argument: "'canvas:drop'", occurrence: 1, state: 'nodePos', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4671, argument: "'canvas:auto-arrange'", occurrence: 1, state: 'nodePos', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4672, argument: "'canvas:align'", occurrence: 1, state: 'nodePos', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4673, argument: "'canvas:distribute'", occurrence: 1, state: 'nodePos', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4675, argument: "'canvas:undo-layout'", occurrence: 1, state: 'nodePos', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4679, argument: "'canvas:edge-from'", occurrence: 1, state: 'edgeList', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4680, argument: "'canvas:edge-to'", occurrence: 1, state: 'edgeList', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4681, argument: "'canvas:edge-delete'", occurrence: 1, state: 'edgeList', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4683, argument: "'canvas:edge-add'", occurrence: 1, state: 'edgeList', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4861, argument: "'group:toggle'", occurrence: 1, state: 'groups', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4871, argument: "'group:rename'", occurrence: 1, state: 'groups', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4875, argument: "'tab:rename'", occurrence: 1, state: 'tabNames', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4948, argument: "'tabs:close-colour'", occurrence: 1, state: 'tabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4959, argument: "'tabs:close-filter'", occurrence: 1, state: 'tabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4984, argument: "'tabs:reorder'", occurrence: 1, state: 'tabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4993, argument: "'tabs:group'", occurrence: 1, state: 'groupsAndTabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 4998, argument: "'tabs:close'", occurrence: 1, state: 'tabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5002, argument: "'tabs:new'", occurrence: 1, state: 'tabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5033, argument: "'preset:max-fun'", occurrence: 1, state: 'values', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5034, argument: "'preset:zero-fun'", occurrence: 1, state: 'values', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5042, argument: "'appearance:reroll'", occurrence: 1, state: 'rndNonce', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5293, argument: "'group:update'", occurrence: 1, state: 'groups', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5320, argument: "'tabs:close-left'", occurrence: 1, state: 'tabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5321, argument: "'tabs:close-right'", occurrence: 1, state: 'tabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5322, argument: "'tabs:close-others'", occurrence: 1, state: 'tabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5326, argument: "'tabs:close-uncoloured'", occurrence: 1, state: 'tabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5327, argument: "'tabs:close-unpinned'", occurrence: 1, state: 'tabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5350, argument: "'group:update'", occurrence: 2, state: 'groups', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5358, argument: "'group:ungroup'", occurrence: 1, state: 'groups', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5359, argument: "'group:close'", occurrence: 1, state: 'groupsAndTabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5373, argument: "'tabs:duplicate'", occurrence: 1, state: 'tabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5374, argument: "'tabs:close'", occurrence: 2, state: 'tabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5376, argument: "'tabs:group-by-area'", occurrence: 1, state: 'groupsAndTabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5419, argument: "'tabs:new-here'", occurrence: 1, state: 'tabs', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5519, argument: "'appearance:reset'", occurrence: 1, state: 'values', clockEffect: 'recorded' },
  { file: 'generated/console.tsx', line: 5617, argument: "'preset:super-easy'", occurrence: 1, state: 'valuesAndOnboarding', clockEffect: 'recorded' }
];
export const ATTENTION_MUTATION_PASSIVE_EXCLUSIONS = [
  { id:'navigation', description:'screen and rail navigation does not change user data' }, { id:'passive-read', description:'PBX reads and refresh timers do not change user data' }, { id:'selection', description:'row, tab, and palette selection does not persist user data' }, { id:'overlay', description:'opening, closing, and moving transient overlays is not a durable mutation' }, { id:'timer', description:'elapsed-time and notification timers do not change user data' },
] as const;
export interface AttentionSeverityProducerSite { readonly id:string; readonly file:string; readonly line:number; readonly column:number; readonly source:string; readonly helper:string; readonly severity:AttentionSeverity; readonly passive:boolean; }
const APP_SEVERITY_PRODUCER_SITES = [
  [255, 35, 'notifyError', 'error', true],
  [256, 42, 'notifyWarning', 'warning', true],
  [257, 14, 'notifyInfo', 'info', false],
  [859, 9, 'notifyMessage', 'info', false],
  [862, 11, 'notifyEvent', 'error', false],
  [896, 13, 'notifyMessage', 'info', false],
  [898, 16, 'notifyEvent', 'error', false],
  [900, 32, 'notifyEvent', 'error', false],
  [909, 9, 'notifyMessage', 'info', false],
  [916, 11, 'notifyEvent', 'warning', false],
  [919, 9, 'notifyMessage', 'info', false],
  [922, 11, 'notifyEvent', 'error', false],
  [930, 9, 'notifyEvent', 'info', false],
  [967, 11, 'notifyEvent', 'error', false],
  [972, 9, 'notifyEvent', 'info', false],
  [1017, 13, 'notifyEvent', 'error', false],
  [1023, 11, 'notifyMessage', 'info', false],
  [1033, 11, 'notifyMessage', 'info', false],
  [1102, 11, 'notifyEvent', 'info', false],
  [1104, 14, 'notifyEvent', 'error', false],
  [1110, 24, 'notifyEvent', 'error', false],
  [1115, 11, 'notifyEvent', 'info', false],
  [1117, 14, 'notifyEvent', 'error', false],
  [1176, 11, 'notifyEvent', 'info', false],
  [1182, 11, 'notifyEvent', 'error', false],
  [1194, 13, 'notifyEvent', 'warning', false],
  [1197, 11, 'notifyMessage', 'info', false],
  [1200, 13, 'notifyEvent', 'error', false],
  [1205, 13, 'notifyEvent', 'warning', false],
  [1224, 11, 'notifyEvent', 'warning', false],
  [1239, 17, 'notifyEvent', 'error', false],
  [1250, 15, 'notifyEvent', 'info', false],
  [1279, 23, 'notifyEvent', 'warning', false],
  [1281, 26, 'notifyEvent', 'warning', false],
  [1285, 9, 'notifyMessage', 'info', false],
  [1320, 13, 'notifyEvent', 'warning', false],
  [1344, 11, 'notifyEvent', 'info', false],
  [1351, 9, 'notifyEvent', 'info', false],
  [1436, 9, 'notifyEvent', 'info', false],
  [1455, 45, 'notifyWarning', 'warning', false],
  [1456, 57, 'notifyWarning', 'warning', false],
  [1457, 50, 'notifyWarning', 'warning', false],
  [1465, 9, 'notifyMessage', 'info', false],
  [1493, 15, 'notifyWarning', 'warning', false],
  [1497, 15, 'notifyWarning', 'warning', false],
  [1501, 13, 'notifyWarning', 'warning', false],
  [1504, 11, 'notifyWarning', 'warning', false],
  [1524, 9, 'notifyEvent', 'info', false],
  [1538, 11, 'notifyInfo', 'info', false],
  [1544, 11, 'notifyWarning', 'warning', false],
  [1550, 9, 'notifyWarning', 'warning', false],
  [1556, 48, 'notifyEvent', 'warning', false],
  [1558, 32, 'notifyEvent', 'error', false],
  [1559, 42, 'notifyMessage', 'info', false],
  [1566, 48, 'notifyEvent', 'warning', false],
  [1569, 35, 'notifyEvent', 'error', false],
  [1581, 33, 'notifyEvent', 'error', false],
  [1590, 11, 'notifyEvent', 'info', false],
  [1598, 29, 'notifyEvent', 'error', false],
  [1600, 29, 'notifyEvent', 'error', false],
  [1605, 9, 'notifyEvent', 'info', false],
  [1741, 38, 'notifyWarningEvent', 'warning', false],
  [2140, 19, 'notifyMessage', 'info', false],
  [2161, 9, 'notifyEvent', 'info', false],
  [2178, 9, 'notifyMessage', 'info', false],
  [2184, 9, 'notifyEvent', 'info', false],
  [2192, 11, 'notifyWarning', 'warning', false],
  [2203, 9, 'notifyMessage', 'info', false],
  [2246, 19, 'notifyError', 'error', true],
  [2246, 72, 'notifyWarning', 'warning', true],
  [2246, 102, 'notifyInfo', 'warning', true],
  [2248, 19, 'notifyErrorEvent', 'error', true],
  [2248, 81, 'notifyWarningEvent', 'warning', true],
  [2248, 120, 'notifyInfoEvent', 'warning', true],
  [2270, 15, 'notifyEvent', 'warning', false],
  [2273, 13, 'notifyMessage', 'info', false],
  [2276, 17, 'notifyEvent', 'error', false],
  [2288, 17, 'notifyEvent', 'error', false],
  [2291, 15, 'notifyEvent', 'info', false],
  [2642, 17, 'notifyMessage', 'info', false],
  [2643, 17, 'notifyError', 'error', false]
] as const;
const GENERATED_SEVERITY_PRODUCER_SITES = [
  [4039, 9, 'notifyInfo', 'info', false],
  [4041, 114, 'notifyInfoEvent', 'info', false],
  [4042, 113, 'notifyWarning', 'warning', false],
  [4043, 38, 'notifyInfo', 'info', false],
  [4044, 30, 'notifyInfoEvent', 'info', false],
  [4143, 13, 'notifyInfoEvent', 'info', false],
  [4147, 28, 'notifyInfoEvent', 'info', false],
  [4148, 14, 'notifyInfo', 'info', false],
  [4356, 9, 'notifyInfoEvent', 'info', false],
  [4369, 9, 'notifyInfoEvent', 'info', false],
  [4377, 103, 'notifyWarning', 'warning', false],
  [4378, 119, 'notifyWarning', 'warning', false],
  [4382, 9, 'notifyInfoEvent', 'info', false],
  [4385, 142, 'notifyInfo', 'info', false],
  [4397, 63, 'notifyInfoEvent', 'info', false],
  [4546, 102, 'notifyInfo', 'info', false],
  [4616, 149, 'notifyInfo', 'info', false],
  [4657, 25, 'notifyInfo', 'info', false],
  [4658, 153, 'notifyInfoEvent', 'info', false],
  [4671, 152, 'notifyInfo', 'info', false],
  [4674, 90, 'notifyInfo', 'info', false],
  [4675, 135, 'notifyInfo', 'info', false],
  [4688, 75, 'notifyInfo', 'info', false],
  [4692, 63, 'notifyInfo', 'info', false],
  [4720, 15, 'notifyWarning', 'warning', false],
  [4770, 174, 'notifyInfo', 'info', false],
  [4872, 22, 'notifyInfo', 'info', false],
  [4876, 13, 'notifyInfo', 'info', false],
  [4895, 242, 'notifyInfo', 'info', false],
  [4945, 46, 'notifyInfo', 'info', false],
  [4949, 22, 'notifyInfo', 'info', false],
  [4960, 13, 'notifyInfo', 'info', false],
  [4994, 15, 'notifyInfoEvent', 'info', false],
  [5008, 128, 'notifyInfo', 'info', false],
  [5032, 141, 'notifyInfoEvent', 'info', false],
  [5033, 368, 'notifyInfoEvent', 'info', false],
  [5034, 218, 'notifyInfo', 'info', false],
  [5035, 180, 'notifyInfoEvent', 'info', false],
  [5042, 124, 'notifyInfo', 'info', false],
  [5045, 145, 'notifyInfo', 'info', false],
  [5048, 64, 'notifyInfoEvent', 'info', false],
  [5049, 64, 'notifyInfo', 'info', false],
  [5050, 62, 'notifyInfoEvent', 'info', false],
  [5051, 70, 'notifyInfo', 'info', false],
  [5053, 65, 'notifyInfo', 'info', false],
  [5079, 99, 'notifyInfo', 'info', false],
  [5080, 93, 'notifyInfo', 'info', false],
  [5081, 98, 'notifyInfoEvent', 'info', false],
  [5095, 23, 'notifyInfo', 'info', false],
  [5106, 32, 'notifyInfo', 'info', false],
  [5127, 101, 'notifyWarning', 'warning', false],
  [5128, 213, 'notifyInfoEvent', 'info', false],
  [5137, 135, 'notifyInfoEvent', 'info', false],
  [5138, 18, 'notifyWarning', 'warning', false],
  [5159, 58, 'notifyInfoEvent', 'info', false],
  [5160, 100, 'notifyWarning', 'warning', false],
  [5165, 99, 'notifyInfoEvent', 'info', false],
  [5165, 263, 'notifyInfo', 'info', false],
  [5183, 17, 'notifyInfoEvent', 'info', false],
  [5188, 57, 'notifyWarning', 'warning', false],
  [5188, 158, 'notifyInfoEvent', 'info', false],
  [5213, 17, 'notifyInfoEvent', 'info', false],
  [5271, 97, 'notifyInfoEvent', 'info', false],
  [5300, 84, 'notifyInfo', 'info', false],
  [5306, 85, 'notifyInfoEvent', 'info', false],
  [5307, 78, 'notifyInfo', 'info', false],
  [5308, 88, 'notifyInfoEvent', 'info', false],
  [5309, 84, 'notifyInfo', 'info', false],
  [5312, 80, 'notifyInfo', 'info', false],
  [5313, 92, 'notifyInfoEvent', 'info', false],
  [5314, 75, 'notifyInfo', 'info', false],
  [5315, 95, 'notifyInfo', 'info', false],
  [5358, 184, 'notifyInfo', 'info', false],
  [5376, 531, 'notifyInfoEvent', 'info', false],
  [5377, 111, 'notifyWarning', 'warning', false],
  [5389, 99, 'notifyInfo', 'info', false],
  [5399, 93, 'notifyInfo', 'info', false],
  [5400, 96, 'notifyInfoEvent', 'info', false],
  [5409, 96, 'notifyInfo', 'info', false],
  [5410, 101, 'notifyInfo', 'info', false],
  [5411, 194, 'notifyInfoEvent', 'info', false],
  [5422, 101, 'notifyInfo', 'info', false],
  [5487, 54, 'notifyWarning', 'warning', false],
  [5488, 66, 'notifyWarning', 'warning', false],
  [5492, 13, 'notifyInfo', 'info', false],
  [5495, 26, 'notifyInfo', 'info', false],
  [5508, 139, 'notifyInfoEvent', 'info', false],
  [5510, 121, 'notifyInfo', 'info', false],
  [5511, 68, 'notifyInfo', 'info', false],
  [5515, 71, 'notifyInfo', 'info', false],
  [5519, 133, 'notifyInfo', 'info', false],
  [5520, 67, 'notifyInfoEvent', 'info', false],
  [5521, 58, 'notifyInfo', 'info', false],
  [5522, 56, 'notifyInfo', 'info', false],
  [5602, 193, 'notifyInfo', 'info', false],
  [5606, 148, 'notifyInfoEvent', 'info', false],
  [5609, 101, 'notifyInfo', 'info', false],
  [5617, 322, 'notifyInfoEvent', 'info', false],
  [5631, 65, 'notifyInfo', 'info', false]
] as const;
export const ATTENTION_SEVERITY_PRODUCERS: readonly AttentionSeverityProducerSite[] = [
  ...APP_SEVERITY_PRODUCER_SITES.map(([line,column,helper,severity,passive]) => ({ id:`App.tsx:${line}:${column}`, file:'App.tsx', line, column, source:`${helper}@${line}:${column}`, helper, severity, passive })),
  ...GENERATED_SEVERITY_PRODUCER_SITES.map(([line,column,helper,severity,passive]) => ({ id:`generated/console.tsx:${line}:${column}`, file:'generated/console.tsx', line, column, source:`${helper}@${line}:${column}`, helper, severity, passive })),
];
export interface AttentionSeverityRoute { readonly id:string; readonly file:'App.tsx'|'generated/console.tsx'; readonly line:number; readonly branches:readonly { readonly input:'error'|'warning'|'default'; readonly helper:string; }[]; }
export const ATTENTION_SEVERITY_ROUTES: readonly AttentionSeverityRoute[] = [
  { id:'ceremony-toast-severity', file:'App.tsx', line:2246, branches:[{ input:'error', helper:'notifyError' }, { input:'warning', helper:'notifyWarning' }, { input:'default', helper:'notifyInfo' }] },
  { id:'ceremony-fire-severity', file:'App.tsx', line:2248, branches:[{ input:'error', helper:'notifyErrorEvent' }, { input:'warning', helper:'notifyWarningEvent' }, { input:'default', helper:'notifyInfoEvent' }] },
];
export interface AttentionStructuredNoticeProducer { readonly id:string; readonly file:'App.tsx'|'generated/console.tsx'; readonly line:number; readonly marker:string; readonly kind:'path'|'url'|'credential'; readonly field:'title'|'body'; }
export const ATTENTION_STRUCTURED_NOTICE_PRODUCERS: readonly AttentionStructuredNoticeProducer[] = [
  { id:'deployment-secrets', file:'App.tsx', line:1249, marker:"sensitiveSpansForValue(deployedBody, entry.secret, 'credential', 'body')", kind:'credential', field:'body' },
  { id:'export-filename', file:'App.tsx', line:1343, marker:"sensitiveSpansForValue(noticeBody, filename, 'path', 'body')", kind:'path', field:'body' },
  { id:'endpoint-secret', file:'App.tsx', line:1589, marker:"sensitiveSpansForValue(noticeBody, draft.secret, 'credential', 'body')", kind:'credential', field:'body' },
];
