line = (
    "- [x] **Map all 32 audited destinations to final reference routes, product routes, and "
    "built-artifact captures after integration.** **Two of the three columns were already real "
    "and the third was a string.** `scripts/generate-design-parity-capture-manifest.mjs` has "
    "generated a row per destination into `design-reference/capture-manifest.generated.json` "
    "for some time -- reference route, product route, every capture and evidence path, and the "
    "real click-sequence navigation plan -- and its `--check` mode is chained into `npm test`, "
    "so the mapping itself was current and guarded. The reference routes resolve against a "
    "harness that exists. The captures are 64 committed PNGs. The product route was "
    "`ding-pbx://destination/{id}`, and **nothing anywhere read one**, so nothing anywhere "
    "could refuse one. The inventory said so in as many words, in "
    "`captureContract.builtRouteStatus`: “a committed route template only; no custom "
    "protocol handler is registered in console/app/ yet.” A column that names an address "
    "nobody answers is wired at one end and consumed at neither, which is this repository's "
    "oldest recurring defect and is invisible from either end on its own. **So the third column "
    "was made real rather than the item ticked over it.** An installed copy registers the scheme "
    "(`app.setAsDefaultProtocolClient`, packaged builds only -- a development checkout "
    "registering it would point the machine's handler at whichever `electron.exe` ran last and "
    "take it from every installed copy on the account); a launch carrying such a URL reads it "
    "off its own command line; a single-instance lock hands a second launch's command line to "
    "the instance already running rather than opening a second console; and the renderer opens "
    "the destination through the compiled shell's own `openScreen`, so **the rail moves with "
    "the screen** rather than landing the destination beside the previous rail's section list. "
    "**What it refuses matters more than what it accepts, and each refusal is by name.** The "
    "route carries the five-part capture tuple and this build cannot honour all five. "
    "`theme=light` has nowhere to land -- the compiled design bakes literal dark-mode hex "
    "colours rather than token references, which is the same reason the `p_theme` control has "
    "no consumer and is recorded beside it in App.tsx. `scale` is the display's own device "
    "scale factor and no window can be told to change it. `state` has one value. `width` and "
    "`height` **are** honoured, applied to the window before it is shown, so the tuple the "
    "route names is the tuple it produces. A refusal is delivered to the renderer and said on "
    "screen, never dropped: a link that silently does nothing cannot be told apart from one the "
    "operating system never routed here at all. **One race was designed out rather than found "
    "later.** A link handed in on the command line is known before the window exists, so pushing "
    "it at the renderer would push it at a listener not yet registered -- the send succeeds, "
    "nothing receives it, and the link does nothing. The renderer pulls on mount instead, and "
    "only once it has pulled, which is proof its listener exists, is a later link pushed. **The "
    "checks are two independent ones, deliberately.** `inventory-validation.mjs` pins the route "
    "template's prefix (both directions broken in `negative-design-parity.mjs`: a foreign scheme, "
    "and this scheme addressing an authority it never defined), and "
    "`tests/control-plane/deep-link.test.ts` feeds every **generated** route through the real "
    "parser and requires each to name the destination of the row it sits in -- the manifest "
    "generates that column from the inventory template rather than from `deepLinkFor`, so it is "
    "a real comparison and not a function agreeing with itself. **What ticking this does not "
    "claim.** No capture was retaken and no destination moved to `verified`; the committed built "
    "captures are still the ones the axis-pin run took, driven exactly as before. The route has "
    "not been exercised by clicking a link in a shell on an installed copy -- it is proved by "
    "the tests and no further -- and the macOS `open-url` path is registered and unexercised, "
    "because this project's delivery scope is Windows. The single-instance lock has a cost that "
    "is documented rather than discovered: `npm start` while an installed copy runs will quit "
    "and focus the installed one, and `--user-data-dir` is the way round it, which is what the "
    "capture harness already passes. **Verification.** Full suite green at `EXIT=0`, "
    "{PASS} pass, 0 fail, zero `not ok` lines, run on the final tree after an earlier run was "
    "invalidated by regenerating the docs bundle underneath it; `npx tsc -b` clean. 35 breaks in "
    "`scripts/negative-deep-link.mjs`, each planted alone, each watched go red and each restored "
    "byte-for-byte -- every refusal, the scheme registration, the single-instance lock, the "
    "second-instance hand-off, both preload files, the renderer's pull and its subscription, "
    "the rail moving with the screen, and two breaks on the generated column itself, which is "
    "the exact state this item found it in. `docs/platform/product-route.md`."
)

import io
p = 'ROADMAP.md'
raw = open(p, encoding='utf-8', newline='').read()
old = "- [ ] Map all 32 audited destinations to final reference routes, product routes, and built-artifact captures after integration."
assert raw.count(old) == 1, raw.count(old)
raw = raw.replace(old, line)
open(p, 'w', encoding='utf-8', newline='').write(raw)
print('ticked')
