#!/usr/bin/env node
/**
 * Measure what actually works and write it into the README.
 *
 * This exists because the README's own "what is not done yet" section had every one of its
 * six bullets go false without anyone noticing: it said nothing had ever been written to an
 * exchange, that the interface carried no accessibility attributes at all, and that no
 * built-artifact captures existed. All three had been true when written and none were true
 * months later. A section like that is worse than an empty one, because a reader has no way
 * to tell a stale claim from a current one and the confident tone reads the same either way.
 *
 * So none of these numbers are typed by hand. Each is read from the thing it describes: the
 * coverage constants from the test that measures coverage, the destination count from the
 * compiled renderer, the accessibility counts from the shipped markup, the roadmap tally from
 * the roadmap. Where something genuinely cannot be measured from the tree — whether a real
 * exchange has been written to — it is read from the roadmap's own checkbox rather than
 * asserted here, so there is exactly one place to change it and this file cannot disagree
 * with it.
 *
 *   node console/scripts/status-block.mjs           # print the block
 *   node console/scripts/status-block.mjs --write   # rewrite README.md between its markers
 *   node console/scripts/status-block.mjs --check   # exit 1 if the README has drifted
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const consoleRoot = resolve(here, '..');
const repoRoot = resolve(consoleRoot, '..');
const read = (p) => readFileSync(resolve(repoRoot, p), 'utf8').replace(/\r\n/gu, '\n');

const BEGIN = '<!-- status-block:begin -->';
const END = '<!-- status-block:end -->';

/* Every reader below returns `undefined` rather than guessing when its source stops looking
 * the way it does today. An unavailable number is printed as "not measurable", which is
 * honest; a number invented to fill the row is the failure this whole file is a reaction to. */
const number = (source, pattern) => {
  const match = source.match(pattern);
  return match ? Number(match[1]) : undefined;
};

const coverage = () => {
  const src = read('console/tests/ui/telephony-coverage.test.tsx');
  return {
    working: number(src, /^const WORKING_FLOOR = (\d+);/mu),
    total: number(src, /^const TELEPHONY_TOTAL = (\d+);/mu),
  };
};

const destinations = () => {
  const src = read('console/app/renderer/src/generated/console.tsx');
  const order = src.match(/const ORDER\s*=\s*\[([\s\S]*?)\]/u);
  return order ? order[1].split(',').filter((entry) => entry.trim().length > 0).length : undefined;
};

const accessibility = () => {
  const src = read('console/app/renderer/src/generated/console.tsx');
  const roles = {};
  for (const m of src.matchAll(/role:\s*`([a-z]+)`/gu)) roles[m[1]] = (roles[m[1]] || 0) + 1;
  return {
    roles: Object.values(roles).reduce((a, b) => a + b, 0),
    landmarks: (roles.banner || 0) + (roles.main || 0) + (roles.navigation || 0),
    dialogs: roles.dialog || 0,
    ariaNames: (src.match(/"aria-label"/gu) || []).length,
  };
};

const roadmap = () => {
  const src = read('ROADMAP.md');
  const done = (src.match(/^- \[x\]/gmu) || []).length;
  const open = (src.match(/^- \[ \]/gmu) || []).length;
  /* Read from the roadmap rather than restated here, so there is one place to change it. */
  const liveExchange = /^- \[x\][^\n]*non-disposable exchange/mu.test(src);
  return { done, open, liveExchange };
};

const inventory = () => {
  try {
    const parity = JSON.parse(read('console/inventories/design-parity.json'));
    const rows = Array.isArray(parity) ? parity : Object.values(parity).find(Array.isArray) || [];
    return { verified: rows.filter((r) => r && r.state === 'verified').length, total: rows.length };
  } catch {
    return { verified: undefined, total: undefined };
  }
};

const site = () => {
  const tests = read('console/site/tests/site.test.mjs');
  return { pages: number(tests, /articles\.length,\s*(\d+)/u), outputs: number(tests, /\?\s*(\d+)\s*:/u) };
};

const show = (value) => (value === undefined ? 'not measurable' : String(value));

const build = () => {
  const cov = coverage();
  const a11y = accessibility();
  const road = roadmap();
  const inv = inventory();
  const dest = destinations();
  const web = site();

  const pct = cov.working && cov.total ? ((cov.working / cov.total) * 100).toFixed(1) : undefined;

  return [
    BEGIN,
    '',
    '> These numbers are generated by `node console/scripts/status-block.mjs`, read from the code',
    '> they describe. They are not typed by hand, because the section they replaced had all six of',
    '> its claims go false without anyone noticing.',
    '',
    '### Does it work?',
    '',
    'Yes, with named limits. It builds, installs, launches, reads a real Asterisk target, and writes',
    'configuration through a transaction that backs up, stages, validates, applies and reads back.',
    '',
    '| Measured | Value |',
    '| --- | ---: |',
    `| Controls that do something | **${show(cov.working)} of ${show(cov.total)}**${pct ? ` (${pct}%)` : ''} |`,
    `| Destinations in the interface | ${show(dest)} |`,
    `| Roadmap items complete | ${show(road.done)} of ${show(road.done + road.open)} |`,
    `| ARIA roles in the shipped markup | ${show(a11y.roles)} |`,
    `| Landmarks / labelled dialogs | ${show(a11y.landmarks)} / ${show(a11y.dialogs)} |`,
    `| Published site pages | ${show(web.pages)} articles, ${show(web.outputs)} output files |`,
    '',
    '### What is not done',
    '',
    `- **Written to a real exchange:** ${road.liveExchange ? 'yes' : '**no** — every write path is proven against a disposable target only'}.`,
    `- **Design-parity evidence:** ${show(inv.verified)} of ${show(inv.total)} destinations verified against captures of the built artifact.`,
    `- **Roadmap items still open:** ${show(road.open)}.`,
    '- **Installers are unsigned by permanent policy**, so Windows shows an unknown-publisher warning.',
    '',
    END,
  ].join('\n');
};

const block = build();
const mode = process.argv.find((a) => a === '--write' || a === '--check');
const readmePath = resolve(repoRoot, 'README.md');
const readme = readFileSync(readmePath, 'utf8');
const nl = readme.includes('\r\n') ? '\r\n' : '\n';
const start = readme.indexOf(BEGIN);
const finish = readme.indexOf(END);

if (mode === '--write') {
  if (start < 0 || finish < 0) { console.error('README has no status-block markers; add them where the block belongs.'); process.exit(1); }
  const next = readme.slice(0, start) + block.split('\n').join(nl) + readme.slice(finish + END.length);
  writeFileSync(readmePath, next);
  console.log('README status block rewritten from measurement.');
} else if (mode === '--check') {
  if (start < 0 || finish < 0) { console.error('FAIL: README has no status-block markers.'); process.exit(1); }
  const current = readme.slice(start, finish + END.length).replace(/\r\n/gu, '\n');
  if (current !== block) {
    console.error('FAIL: the README status block no longer matches what the code measures.');
    console.error('Run: node console/scripts/status-block.mjs --write');
    process.exit(1);
  }
  console.log('PASS: the README status block matches the measurements.');
} else {
  console.log(block);
}
